YOLOV3:
  CFG: "./detector/YOLOv3/cfg/yolov3-sport-606.cfg"
  WEIGHT: "./detector/YOLOv3/weight/yolov3_sport_606.weights"
  CLASS_NAMES: "./detector/YOLOv3/cfg/sport.names"

  SCORE_THRESH: 0.5
  NMS_THRESH: 0.4
